//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3070.DbModelCore
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Collections.Generic;
    
    public partial class Demographic
    {
               
    
        public int demographic_no { get; set; }
        public string title { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string postal { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string email { get; set; }
        public string myOscarUserName { get; set; }
        public string year_of_birth { get; set; }
        public string month_of_birth { get; set; }
        public string date_of_birth { get; set; }
        public string hin { get; set; }
        public string ver { get; set; }
        public string roster_status { get; set; }
        public Nullable<System.DateTime> roster_date { get; set; }
        public Nullable<System.DateTime> roster_termination_date { get; set; }
        public string roster_termination_reason { get; set; }
        public string patient_status { get; set; }
        public Nullable<System.DateTime> patient_status_date { get; set; }
        public Nullable<System.DateTime> date_joined { get; set; }
        public string chart_no { get; set; }
        public string official_lang { get; set; }
        public string spoken_lang { get; set; }
        public string provider_no { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> eff_date { get; set; }
        public string pcn_indicator { get; set; }
        public string hc_type { get; set; }
        public Nullable<System.DateTime> hc_renew_date { get; set; }
        public string family_doctor { get; set; }
        public string alias { get; set; }
        public string previousAddress { get; set; }
        public string children { get; set; }
        public string sourceOfIncome { get; set; }
        public string citizenship { get; set; }
        public string sin { get; set; }
        public string country_of_origin { get; set; }
        public string newsletter { get; set; }
        public string anonymous { get; set; }
        public string lastUpdateUser { get; set; }
        public System.DateTime lastUpdateDate { get; set; }
        public string patient_type { get; set; }
        public string patient_id { get; set; }
        public string pref_name { get; set; }
        public Nullable<byte> consentToUseEmailForCare { get; set; }
    
       
    }
    [Keyless]
    public class DemographicUpdate
    {


        public int demographic_no { get; set; }
        public string patient_id { get; set; }
        public string title { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string sex { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string postal { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; } 
        
        public string ver { get; set; }  //Health region
        public string email { get; set; } 
        public string hin { get; set; }
        
        public string year_of_birth { get; set; }
        public string month_of_birth { get; set; }
        public string date_of_birth { get; set; }
       
            
        public string provider_no { get; set; }
        public string patient_status { get; set; }

        public string family_doctor { get; set; }

        public string alias { get; set; }



    }
}
