//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3070.DbModelCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string contactName { get; set; }
        public string contactEmail { get; set; }
        public string contactPhone { get; set; }
        
        public int orgId { get; set; }
        public int sectorId { get; set; }
        public byte integratorEnabled { get; set; }
        public string integratorUrl { get; set; }
       
        
        public System.DateTime lastUpdated { get; set; }
        
        public Nullable<int> registrationIntake { get; set; }
        public int rxInteractionWarningLevel { get; set; }
        public int displayAllVacancies { get; set; }
        public string vacancyWithdrawnTicklerProvider { get; set; }
        public Nullable<int> vacancyWithdrawnTicklerDemographic { get; set; }
        public string assignNewVacancyTicklerProvider { get; set; }
        public Nullable<int> assignNewVacancyTicklerDemographic { get; set; }
        public string assignRejectedVacancyApplicant { get; set; }
    
        
    }
}
