//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3070.DbModelCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public string name { get; set; }
        public string value { get; set; }
        public int id { get; set; }
        public string provider_no { get; set; }
    }
}
