//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3070.DbModelCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public string provider_no { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string provider_type { get; set; }
        public string supervisor { get; set; }
        public string specialty { get; set; }
        public string team { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string work_phone { get; set; }
        public string ohip_no { get; set; }
        public string rma_no { get; set; }
        public string billing_no { get; set; }
        public string hso_no { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
        public string provider_activity { get; set; }
        public string practitionerNo { get; set; }
        public string init { get; set; }
        public string job_title { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string lastUpdateUser { get; set; }
        public System.DateTime lastUpdateDate { get; set; }
        public Nullable<System.DateTime> signed_confidentiality { get; set; }
        public bool thirdPartyOnly { get; set; }
        public string practitionerNoType { get; set; }
    }
}
