//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3070.DbModelCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDate
    {
        public int id { get; set; }
        public System.DateTime sdate { get; set; }
        public string provider_no { get; set; }
        public string available { get; set; }
        public string priority { get; set; }
        public string reason { get; set; }
        public string hour { get; set; }
        public string creator { get; set; }
        public string status { get; set; }
    }
}
