//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM3070.DbModelCore
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDate
    {
        public int id { get; set; }
        public DateTime sdate { get; set; }
        public string provider_no { get; set; }
        public string available { get; set; }
        public string priority { get; set; }
        public string reason { get; set; }
        public string hour { get; set; }
        public string creator { get; set; }
        public string status { get; set; }
        public int demographic_no { get; set; }
    }

    [Keyless]
    public class SchaduleEventDetail
    {
        public DateTime date { get; set; }
        public char available { get; set; }
        public char priority { get; set; }
        public string? reason { get; set; }
        public string? hour { get; set; }
        public string? creator { get; set; }
        public char status { get; set; }
        public string? provider_lname { get; set; }
        public string? provider_fname { get; set; }
        public string? specialty { get; set; }

        public string first_name { get; set; } = string.Empty;
        public string last_name { get; set; } = string.Empty;
    }
}
